Unit test
etherspot/arka pull request #59
Opened 2024-01-25 13:37 UTC by Jineshdarjee

## Description
* Added unit test cases for the Paymaster > index.ts file

2024-01-31 08:29 UTC, IAmKio approved these changes
LGTM

2024-02-05 19:25 UTC, ch4r10t33r requested changes

2024-02-05 19:25 UTC, ch4r10t33r commented on backend/src/paymaster/pimlico.test.ts
> +      await pimlicoPaymaster.generatePaymasterAndData(userOp);
I don't see any assertion here? How is this supposed to work? What am I missing?

2024-02-05 19:25 UTC, ch4r10t33r commented on backend/src/paymaster/pimlico.test.ts
> +      await getERC20Paymaster(provider, erc20, entryPointAddress, ERC20PaymasterBuildOptions);
Please above. How is this a unit test? Where are we checking for happy path?

2024-02-06 14:31 UTC, Jineshdarjee commented
## Description
* Added the assertion in the unit test cases 
* Bifurcated the smoke (happy path) and regression test cases for better clarity.

CC: @ch4r10t33r

2024-02-09 13:37 UTC, ch4r10t33r approved these changes

2024-02-12 08:02 UTC, vignesha22 requested changes
Please undo the deletion of config.json.default pls since it's the initial setup file required

2024-02-12 09:14 UTC, Jineshdarjee commented
@vignesha22 Added config.json file.

2024-02-12 09:15 UTC, vignesha22 approved these changes
LGTM

2024-02-12 09:18 UTC, merged